server:
  port: 8080

vendors:
  vendor_a:
    name: "vendor_a"
    base_url: "https://api.vendor-a.com"
    api_key: "abc123"
    secret: "shhh_secret"
    timeout_sec: 5
    currency: "USD"
