// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"idv/chris/robot"
)

// Injectors from wire.go:

// InitializeRobot 是一個 Injector 函式，它會指示 wire 建立一個 *robot.Robot 物件
// 它會使用 RobotSet 中的提供者來滿足依賴
func InitializeRobot() *robot.Robot {
	robotArm := robot.NewRobotArm()
	robotHead := robot.NewRobotHead()
	robotRobot := robot.NewRobot(robotArm, robotHead)
	return robotRobot
}

// wire.go:

// ProviderSet，將所有 robot 套件的提供者組織起來
var RobotSet = wire.NewSet(robot.NewRobot, robot.NewRobotArm, robot.NewRobotHead)
