// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"idv/chris/app"
)

// Injectors from wire.go:

// Injector 函式，它定義了最終回傳的物件型別 (*app.Greeter)
// 這告訴 wire 我們的目標是組裝一個完整的 Greeter 服務
func InitializeGreeter() *app.Greeter {
	messageSender := app.NewEmailSender()
	greeter := app.NewGreeter(messageSender)
	return greeter
}

// 如果我們想換成用簡訊發送，只需要修改這裡，換成 NewSMSSender 即可
func InitializeSMSGreeter() *app.Greeter {
	messageSender := app.NewSMSSender()
	greeter := app.NewGreeter(messageSender)
	return greeter
}
